#!/usr/bin/env node
// Regenerates romsets.json — for every arcade set of the bundled FinalBurn Neo core that needs zips besides its own,
// which ones: FBNeo's libretro open_archive() opens up to three zips by name from the romset's directory, in
// BurnGetZipName order: the romset, then its board ROM / BIOS (BurnDriver.szBoardROM) if it has one, else its parent,
// then the parent (board ROM sets) or the grandparent. Read straight out of the shipped core, so the table matches it:
// the wasm's active data segments rebuild the static memory, where pDriver[] (the driver table) is the longest run of
// pointers to BurnDriver structs (src/burn/burnint.h). Console sets (md_, nes_, msx_, …) are left out.
//
//   node src/romsets.mjs emulatorjs/cores/fbneo-legacy-wasm.data > romsets.json      (needs 7z on PATH)
//
// Repo-maintenance script (src/ stays out of the release zip). Re-run whenever fetch-deps.sh pins another core.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { basename } from 'node:path';

const data = process.argv[2];
if (!data) { console.error('usage: node src/romsets.mjs emulatorjs/cores/fbneo-legacy-wasm.data > romsets.json'); process.exit(1); }
const b = execFileSync('7z', ['x', '-so', data, 'fbneo_libretro.wasm'], { maxBuffer: 1 << 28 });

// wasm data section (id 11): active segments (flags 0, i32.const offset) → linear memory
let p = 8;
const uleb = () => { let r = 0, s = 0, x; do { x = b[p++]; r |= (x & 0x7f) << s; s += 7; } while (x & 0x80); return r >>> 0; };
const segs = [];
while (p < b.length) {
  const id = b[p++], end = uleb() + p;
  if (id === 11) {
    for (let n = uleb(); n > 0; n--) {
      if (uleb() !== 0) throw new Error('passive data segment: not the build this script reads');
      p++; // i32.const
      let off = 0, s = 0, x; do { x = b[p++]; off |= (x & 0x7f) << s; s += 7; } while (x & 0x80);
      p++; // end
      const size = uleb();
      segs.push({ off: off >>> 0, at: p, size });
      p += size;
    }
  }
  p = end;
}
const top = Math.max(...segs.map((s) => s.off + s.size)), mem = new Uint8Array(top);
for (const s of segs) mem.set(b.subarray(s.at, s.at + s.size), s.off);
const dv = new DataView(mem.buffer), u32 = (a) => dv.getUint32(a, true);
const str = (a) => { if (!a || a >= top) return null; let e = a; while (e < top && mem[e] && e - a < 300) e++; return mem[e] === 0 ? Buffer.from(mem.subarray(a, e)).toString('latin1') : null; };

// struct BurnDriver: +0 szShortName, +4 szParent, +8 szBoardROM, +20 szFullNameA, +52 Flags, +60 Hardware
const isDriver = (a) => a % 4 === 0 && a + 64 <= top && /^[a-z0-9_]{1,32}$/.test(str(u32(a)) ?? '') && str(u32(a + 20)) !== null;
let table = { at: 0, n: 0 };
for (let a = 0; a + 4 <= top; a += 4) {
  if (!isDriver(u32(a))) continue;
  let n = 0;
  while (a + n * 4 + 4 <= top && isDriver(u32(a + n * 4))) n++;
  if (n > table.n) table = { at: a, n };
  a += n * 4;
}
const opt = (a) => (a ? str(a) : '');
const drivers = new Map();
for (let i = 0; i < table.n; i++) {
  const d = u32(table.at + i * 4), name = str(u32(d));
  if (!drivers.has(name)) drivers.set(name, { parent: opt(u32(d + 4)), board: opt(u32(d + 8)), title: str(u32(d + 20)), flags: u32(d + 52), hw: (u32(d + 60) >>> 24) & 0x7f });
}
// HARDWARE_PREFIX_* (src/burn/burn.h) of the consoles FBNeo also emulates
const CONSOLE = new Set([0x0c, 0x12, 0x17, 0x18, 0x19, 0x1a, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x21, 0x22, 0x24, 0x25]);
const BDF_BOARDROM = 1 << 3;

const groups = new Map(), titles = {}, bios = new Set();
for (const [name, d] of [...drivers].sort(([a], [b]) => (a < b ? -1 : 1))) {
  if (CONSOLE.has(d.hw)) continue;
  const zips = d.board ? [d.board, d.parent] : [d.parent, drivers.get(d.parent)?.parent];
  const need = zips.filter(Boolean);
  if (!need.length) continue;
  for (const z of need) {
    const zd = drivers.get(z);
    if (!zd) throw new Error(`${name} needs ${z}, which is not in the driver table`);
    titles[z] = zd.title;
    if (zd.flags & BDF_BOARDROM) bios.add(z);
  }
  const k = need.join(' ');
  if (!groups.has(k)) groups.set(k, []);
  groups.get(k).push(name);
}
for (const [set, z] of [['kof97', 'neogeo'], ['kov115', 'pgm kov']]) {
  if (![...groups].some(([k, v]) => k === z && v.includes(set))) throw new Error(`sanity check failed: ${set} should need ${z}`);
}

const entries = (o) => Object.entries(o).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
const sorted = (o) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => (a < b ? -1 : 1)));
const sha = createHash('sha256').update(readFileSync(data)).digest('hex');
process.stdout.write(`{
  "source": ${JSON.stringify(`${basename(data)} sha256 ${sha} — ${drivers.size} drivers; generated by src/romsets.mjs`)},
  "bios": ${JSON.stringify([...bios].sort())},
  "titles": {
${entries(sorted(titles))}
  },
  "needs": {
${entries(Object.fromEntries([...groups].sort(([a], [b]) => (a < b ? -1 : 1)).map(([k, v]) => [k, v.join(' ')])))}
  }
}
`);
console.error(`[romsets] ${table.n} driver pointers at ${table.at}, ${drivers.size} drivers; ${[...groups.values()].flat().length} arcade sets need other zips (${groups.size} groups, ${bios.size} BIOS / board ROMs)`);
